# SpendDNA – Personal Spending Analysis

## Project Overview

SpendDNA is a personal finance analytics project that analyzes transaction data
to understand spending patterns, vendors, categories, monthly trends,
time-of-day behavior, anomalies, and spending archetypes.

## Objectives

- Clean and standardize transaction data
- Extract and standardize vendors
- Categorize transactions
- Calculate spending statistics
- Analyze monthly spending trends
- Analyze time-of-day spending patterns
- Detect unusual transactions
- Identify spending archetypes

## Technologies Used

- Python
- Pandas
- NumPy
- Google Colab

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("rahul_transactions.csv")
df.head()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962

In [ ]:
df.shape

(1328, 8)

In [ ]:
df.columns

Index(['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode',
       'Ref'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1328 entries, 0 to 1327
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         1328 non-null   object
 1   Time         1328 non-null   object
 2   Description  1328 non-null   object
 3   Type         1328 non-null   object
 4   Amount       1328 non-null   object
 5   Balance      1328 non-null   float64
 6   Mode         1328 non-null   object
 7   Ref          1328 non-null   object
dtypes: float64(1), object(7)
memory usage: 83.1+ KB

In [ ]:
raw_df = df.copy()

In [ ]:
df.isnull().sum()

Date           0
Time           0
Description    0
Type           0
Amount         0
Balance        0
Mode           0
Ref            0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(18)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(1310, 8)

In [ ]:
df["Date"].head(20)

0      2024-01-01
1       01-Jan-24
2       01-Jan-24
3      2024-01-01
4     01 Jan 2024
5      2024-01-01
6      2024-01-01
7       01-Jan-24
8      2024-01-02
9        02/01/24
10       02/01/24
11      02-Jan-24
12       02/01/24
13    02 Jan 2024
14      02-Jan-24
15       02/01/24
16     2024-01-02
17       02/01/24
18      03-Jan-24
19       03/01/24
Name: Date, dtype: object

In [ ]:
df["Date"] = pd.to_datetime(
    df["Date"],
    errors="coerce",
    dayfirst=True
)

In [ ]:
df["Date"].head()

0   2024-01-01
1          NaT
2          NaT
3   2024-01-01
4          NaT
Name: Date, dtype: datetime64[ns]

In [ ]:
df["Date"].isnull().sum()

np.int64(1184)

In [ ]:
df["Date"].head(20)

0    2024-01-01
1           NaT
2           NaT
3    2024-01-01
4           NaT
5    2024-01-01
6    2024-01-01
7           NaT
8    2024-02-01
9           NaT
10          NaT
11          NaT
12          NaT
13          NaT
14          NaT
15          NaT
16   2024-02-01
17          NaT
18          NaT
19          NaT
Name: Date, dtype: datetime64[ns]

In [ ]:
df["Date"].dropna().unique()[:30]

<DatetimeArray>
['2024-01-01 00:00:00', '2024-02-01 00:00:00', '2024-03-01 00:00:00',
 '2024-04-01 00:00:00', '2024-05-01 00:00:00', '2024-07-01 00:00:00',
 '2024-08-01 00:00:00', '2024-09-01 00:00:00', '2024-10-01 00:00:00',
 '2024-12-01 00:00:00', '2024-01-02 00:00:00', '2024-02-02 00:00:00',
 '2024-03-02 00:00:00', '2024-05-02 00:00:00', '2024-06-02 00:00:00',
 '2024-07-02 00:00:00', '2024-08-02 00:00:00', '2024-11-02 00:00:00',
 '2024-12-02 00:00:00', '2024-01-03 00:00:00', '2024-02-03 00:00:00',
 '2024-03-03 00:00:00', '2024-04-03 00:00:00', '2024-05-03 00:00:00',
 '2024-06-03 00:00:00', '2024-07-03 00:00:00', '2024-09-03 00:00:00',
 '2024-10-03 00:00:00', '2024-11-03 00:00:00', '2024-12-03 00:00:00']
Length: 30, dtype: datetime64[ns]

In [ ]:
df["Date"].dtype

dtype('<M8[ns]')

In [ ]:
df = pd.read_csv("rahul_transactions.csv")

In [ ]:
df["Date"].head(20)

0      2024-01-01
1       01-Jan-24
2       01-Jan-24
3      2024-01-01
4     01 Jan 2024
5      2024-01-01
6      2024-01-01
7       01-Jan-24
8      2024-01-02
9        02/01/24
10       02/01/24
11      02-Jan-24
12       02/01/24
13    02 Jan 2024
14      02-Jan-24
15       02/01/24
16     2024-01-02
17       02/01/24
18      03-Jan-24
19       03/01/24
Name: Date, dtype: object

In [ ]:
df["Amount"].head(20)

0        ₹2462
1        50.00
2       ₹84728
3        ₹1828
4       270.00
5      Rs. 625
6      Rs. 148
7         ₹482
8      Rs. 537
9         3956
10        ₹350
11        ₹311
12      258.00
13        ₹571
14      266.00
15        ₹405
16      267.00
17      Rs. 48
18       ₹1411
19    2,557.00
Name: Amount, dtype: object

In [ ]:
df["Amount"] = (
    df["Amount"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace("Rs.", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

In [ ]:
df["Amount"] = pd.to_numeric(
    df["Amount"],
    errors="coerce"
)

In [ ]:
df["Amount"].head()

0     2462.0
1       50.0
2    84728.0
3     1828.0
4      270.0
Name: Amount, dtype: float64

In [ ]:
df["Amount"].dtype

dtype('float64')

In [ ]:
df["Type"].value_counts()

Type
DR       670
Debit    652
CR         6
Name: count, dtype: int64

In [ ]:
df["Type"] = df["Type"].astype(str).str.strip().str.lower()

In [ ]:
df["Type"].value_counts()

Type
dr       670
debit    652
cr         6
Name: count, dtype: int64

In [ ]:
df["Type"] = df["Type"].replace({
    "dr": "debit",
    "cr": "credit"
})

In [ ]:
df["Type"].value_counts()

Type
debit     1322
credit       6
Name: count, dtype: int64

In [ ]:
df["Description"] = (
    df["Description"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [ ]:
df["Description"].head(20)

0                   AMAZON SELLER SVCS
1                            BHIM-BMTC
2     NEFT-TECHCRUSH LABS-SALARY MAY24
3                 UPI-AMAN-8934@OKAXIS
4                         BHIM-BLINKIT
5                           BHIM ZEPTO
6               UPI-UBER-2426@HDFCBANK
7                         BHIM-BLINKIT
8                 POS SWIGGY BANGALORE
9                UPI-GROWWPAY@HDFCBANK
10                        OLA ELECTRIC
11                   BMS MOVIE TICKETS
12                       POS OLA-PRIME
13                    SWIGGY-INSTAMART
14                  UPI-STARBUCKS@AXIS
15                UPI-THIRDWAVE@OKAXIS
16                    ANI TECHNOLOGIES
17                       BMTC BUS PASS
18                        POS TRUFFLES
19                      FLIPKART INDIA
Name: Description, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1328 entries, 0 to 1327
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         1328 non-null   object
 1   Time         1328 non-null   object
 2   Description  1328 non-null   object
 3   Type         1328 non-null   object
 4   Amount       1328 non-null   float64
 5   Balance      1328 non-null   float64
 6   Mode         1328 non-null   object
 7   Ref          1328 non-null   object
dtypes: float64(2), object(6)
memory usage: 83.1+ KB

In [ ]:
df.head()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,debit,2462.0,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,debit,50.0,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,credit,84728.0,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,debit,1828.0,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,debit,270.0,680737.0,UPI,TXN968962

In [ ]:
import pandas as pd

df = pd.read_csv("rahul_transactions.csv")

In [ ]:
df["Date"].head(20)

0      2024-01-01
1       01-Jan-24
2       01-Jan-24
3      2024-01-01
4     01 Jan 2024
5      2024-01-01
6      2024-01-01
7       01-Jan-24
8      2024-01-02
9        02/01/24
10       02/01/24
11      02-Jan-24
12       02/01/24
13    02 Jan 2024
14      02-Jan-24
15       02/01/24
16     2024-01-02
17       02/01/24
18      03-Jan-24
19       03/01/24
Name: Date, dtype: object

In [ ]:
df["Date"].dtype

dtype('O')

In [ ]:
df["Date"].head(20).tolist()

['2024-01-01',
 '01-Jan-24',
 '01-Jan-24',
 '2024-01-01',
 '01 Jan 2024',
 '2024-01-01',
 '2024-01-01',
 '01-Jan-24',
 '2024-01-02',
 '02/01/24',
 '02/01/24',
 '02-Jan-24',
 '02/01/24',
 '02 Jan 2024',
 '02-Jan-24',
 '02/01/24',
 '2024-01-02',
 '02/01/24',
 '03-Jan-24',
 '03/01/24']

In [ ]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce", dayfirst=False)
df["Date"].isnull().sum()
df["Year"] = df["Date"].dt.year
df["Date"].head(20).tolist()

[Timestamp('2024-01-01 00:00:00'),
 NaT,
 NaT,
 Timestamp('2024-01-01 00:00:00'),
 NaT,
 Timestamp('2024-01-01 00:00:00'),
 Timestamp('2024-01-01 00:00:00'),
 NaT,
 Timestamp('2024-01-02 00:00:00'),
 NaT,
 NaT,
 NaT,
 NaT,
 NaT,
 NaT,
 NaT,
 Timestamp('2024-01-02 00:00:00'),
 NaT,
 NaT,
 NaT]

In [ ]:
df["Year"] = df["Date"].dt.year

In [ ]:
df["Month"] = df["Date"].dt.month

In [ ]:
df["Month_Name"] = df["Date"].dt.strftime("%B")

In [ ]:
df["Day"] = df["Date"].dt.day

In [ ]:
df["Day_Name"] = df["Date"].dt.strftime("%A")

In [ ]:
df.head()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref,Year,Month,Month_Name,Day,Day_Name
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872,2024.0,1.0,January,1.0,Monday
1,NaT,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064,NaN,NaN,NaN,NaN,NaN
2,NaT,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316,NaN,NaN,NaN,NaN,NaN
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226,2024.0,1.0,January,1.0,Monday
4,NaT,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962,NaN,NaN,NaN,NaN,NaN

In [ ]:
df["Time"].head(20)

0     03:11
1     05:44
2     09:35
3     14:07
4     14:23
5     14:48
6     14:50
7     21:44
8     05:18
9     06:55
10    07:26
11    07:39
12    11:29
13    12:35
14    14:01
15    15:42
16    20:58
17    22:33
18    00:55
19    11:29
Name: Time, dtype: object

In [ ]:
df["Hour"] = pd.to_datetime(
    df["Time"],
    format="%H:%M",
    errors="coerce"
).dt.hour

In [ ]:
df[["Time", "Hour"]].head(20)

     Time  Hour
0   03:11     3
1   05:44     5
2   09:35     9
3   14:07    14
4   14:23    14
5   14:48    14
6   14:50    14
7   21:44    21
8   05:18     5
9   06:55     6
10  07:26     7
11  07:39     7
12  11:29    11
13  12:35    12
14  14:01    14
15  15:42    15
16  20:58    20
17  22:33    22
18  00:55     0
19  11:29    11

In [ ]:
pd.set_option("display.max_colwidth", None)

df[["Description"]].head(50)

                         Description
0                 AMAZON SELLER SVCS
1                          BHIM-BMTC
2   NEFT-TECHCRUSH LABS-SALARY MAY24
3               UPI-AMAN-8934@OKAXIS
4                       BHIM-BLINKIT
5                         BHIM ZEPTO
6             UPI-UBER-2426@HDFCBANK
7                       BHIM-BLINKIT
8               POS SWIGGY BANGALORE
9              UPI-GROWWPAY@HDFCBANK
10                      OLA ELECTRIC
11                 BMS MOVIE TICKETS
12                     POS OLA-PRIME
13                  SWIGGY-INSTAMART
14                UPI-STARBUCKS@AXIS
15              UPI-THIRDWAVE@OKAXIS
16                  ANI Technologies
17                     BMTC BUS PASS
18                      POS TRUFFLES
19                    FLIPKART INDIA
20             POS SWIGGY-RESTAURANT
21                 GROFERS INDIA P L
22                POS UBER BANGALORE
23             POS SWIGGY-RESTAURANT
24             BANGALORE ELEC SUPPLY
25                         TWC INDIA
26          UPI-BESCOM-BILL@HDFCBANK
27              UPI-AMAN-0816@OKAXIS
28             ROPPEN TRANSPORTATION
29                UPI-STARBUCKS@AXIS
30                          OLA CABS
31                        POS ZOMATO
32            UPI-AMAZONPAY@HDFCBANK
33                       POS BLINKIT
34       IMPS-RENT-LANDLORD-75500265
35                  ZOMATO MEDIA P L
36             UPI-ANKIT-6430@OKAXIS
37                        BHIM ZEPTO
38              UPI-OLACABS@HDFCBANK
39                        POS ZOMATO
40             UPI-JIORECHARGE@PAYTM
41                  UPI-CCD@HDFCBANK
42                      Swiggy*Order
43               INSTAMART BANGALORE
44          UPI-ZOMATO-LIMITED@PAYTM
45                 AVENUE SUPERMARTS
46                 GROFERS INDIA P L
47             POS HP PETROL STATION
48             UPI-VIKAS-6060@OKAXIS
49          POS BANGALORE RESTAURANT

In [ ]:
def extract_vendor(description):

    text = str(description).upper()

    if "SWIGGY" in text or "BUNDL" in text:
        return "Swiggy"

    elif "ZOMATO" in text:
        return "Zomato"

    elif "AMAZON" in text or "AMZN" in text:
        return "Amazon"

    elif "ZEPTO" in text:
        return "Zepto"

    elif "ZERODHA" in text:
        return "Zerodha"

    elif "UBER" in text:
      return "uber"

    elif "OLA" in text:
      return "ola"

    elif "NETFLIX" in text:
      return "netflix"

    else:
      return "other"

In [ ]:
df["Vendor"] = df["Description"].apply(extract_vendor)

In [ ]:
df["Vendor"].value_counts()

Vendor
other      665
Swiggy     228
Zomato     124
Amazon      87
uber        71
ola         69
Zepto       60
Zerodha     14
netflix     10
Name: count, dtype: int64

In [ ]:
category_mapping = {
    "Swiggy": "Food Delivery",
    "Zomato": "Food Delivery",
    "Zepto": "Quick Commerce",
    "Amazon": "E-commerce",
    "Zerodha": "Investments",
    "Uber": "Transport",
    "Ola": "Transport",
    "Netflix": "Subscriptions"
}

In [ ]:
df["Category"] = df["Vendor"].map(category_mapping)

In [ ]:
df["Category"] = df["Category"].fillna("Other")

In [ ]:
df["Category"].value_counts()

Category
Other             815
Food Delivery     352
E-commerce         87
Quick Commerce     60
Investments        14
Name: count, dtype: int64

In [ ]:
total_credits = df.loc[
    df["Type"] == "credit",
    "Amount"
].sum()

total_credits

0

In [ ]:
total_debits = df.loc[
    df["Type"] == "debit",
    "Amount"
].sum()

total_debits

0

In [ ]:
net_change = total_credits - total_debits

In [ ]:
import numpy as np # Added import for numpy
if total_credits != 0:
    savings_rate = (
        (total_credits - total_debits)
        / total_credits
    ) * 100
else:
    savings_rate = np.nan

In [ ]:
print("Total Credits:", total_credits)
print("Total Debits:", total_debits)
print("Net Change:", net_change)
print("Savings Rate:", savings_rate)

Total Credits: 0
Total Debits: 0
Net Change: 0
Savings Rate: nan

In [ ]:
debit_df = df[df["Type"] == "debit"]

In [ ]:
top_categories = (
    debit_df.groupby("Category")["Amount"]
    .sum()
    .sort_values(ascending=False)
)

In [ ]:
top_categories.head(10)

Series([], Name: Amount, dtype: object)

In [ ]:
top_vendors = (
    debit_df.groupby("Vendor")["Amount"]
    .sum()
    .sort_values(ascending=False)
)

In [ ]:
top_vendors.head(10)

Series([], Name: Amount, dtype: object)

In [ ]:
monthly_spending = (
    debit_df.groupby("Month_Name")["Amount"]
    .sum()
)

In [ ]:
month_order = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
]

In [ ]:
monthly_spending = monthly_spending.reindex(
    month_order
).dropna()

In [ ]:
monthly_spending

Series([], Name: Amount, dtype: object)

In [ ]:
monthly_category = pd.pivot_table(
    debit_df,
    values="Amount",
    index="Category",
    columns="Month_Name",
    aggfunc="sum"
)

In [ ]:
monthly_category

Empty DataFrame
Columns: []
Index: []

In [ ]:
hourly_spending = (
    debit_df.groupby("Hour")["Amount"]
    .sum()
    .sort_values(ascending=False)
)

In [ ]:
hourly_spending

Series([], Name: Amount, dtype: object)

In [ ]:
hourly_transactions = (
    debit_df.groupby("Hour")
    .size()
    .sort_values(ascending=False)
)

In [ ]:
food_delivery = debit_df[
    debit_df["Category"] == "Food Delivery"
]

In [ ]:
late_night_food = food_delivery[
    (food_delivery["Hour"] >= 21) |
    (food_delivery["Hour"] <= 1)
]

In [ ]:
if len(food_delivery) > 0:
    late_night_percentage = (
        len(late_night_food)
        / len(food_delivery)
    ) * 100
else:
    late_night_percentage = np.nan

In [ ]:
print(
    "Late-night Food Delivery:",
    round(late_night_percentage, 2),
    "%"
)

Late-night Food Delivery: nan %

In [ ]:
category_mean = (
    debit_df.groupby("Category")["Amount"]
    .transform("mean")
)

In [ ]:
category_std = (
    debit_df.groupby("Category")["Amount"]
    .transform("std")
)

In [ ]:
debit_df = debit_df.copy()

debit_df["Z_Score"] = (
    (debit_df["Amount"] - category_mean)
    / category_std
)

In [ ]:
anomalies = debit_df[
    debit_df["Z_Score"] > 2
]

In [ ]:
anomalies = anomalies.sort_values(
    "Z_Score",
    ascending=False
)

In [ ]:
anomalies[
    ["Date", "Description", "Vendor",
     "Category", "Amount", "Z_Score"]
].head(10)

Empty DataFrame
Columns: [Date, Description, Vendor, Category, Amount, Z_Score]
Index: []

In [ ]:
category_percentage = (
    top_categories / total_debits
) * 100

In [ ]:
food_percentage = category_percentage.get(
    "Food Delivery",
    0
)

In [ ]:
investment_percentage = category_percentage.get(
    "Investments",
    0
)

In [ ]:
archetypes = []

In [ ]:
if food_percentage > 15:
    archetypes.append("THE FOODIE")

In [ ]:
if investment_percentage > 15:
    archetypes.append("THE INVESTOR")

In [ ]:
ecommerce_percentage = category_percentage.get(
    "E-commerce",
    0
)

if ecommerce_percentage > 15:
    archetypes.append("THE SHOPAHOLIC")

In [ ]:
if late_night_percentage > 50:
    archetypes.append("THE LATE-NIGHT SNACKER")

In [ ]:
if savings_rate < 10:
    archetypes.append("THE YOLO SPENDER")

In [ ]:
print("Spending Archetypes:")

for archetype in archetypes:
    print("-", archetype)

Spending Archetypes:

In [ ]:
print("=" * 60)
print("                 SPENDDNA REPORT")
print("=" * 60)

print("\nTRANSACTION SUMMARY")
print("-" * 60)

print(f"Total Credits : ₹{total_credits:,.2f}")
print(f"Total Debits  : ₹{total_debits:,.2f}")
print(f"Net Change    : ₹{net_change:,.2f}")
print(f"Savings Rate  : {savings_rate:.2f}%")
print(f"Transactions  : {len(df)}")

print("\nTOP CATEGORIES")
print("-" * 60)

print(top_categories.head(5))

print("\nTOP VENDORS")
print("-" * 60)

print(top_vendors.head(5))

print("\nSPENDING ARCHETYPES")
print("-" * 60)

for archetype in archetypes:
    print("→", archetype)

print("\n" + "=" * 60)

============================================================
                 SPENDDNA REPORT
============================================================

TRANSACTION SUMMARY
------------------------------------------------------------
Total Credits : ₹0.00
Total Debits  : ₹0.00
Net Change    : ₹0.00
Savings Rate  : nan%
Transactions  : 1328

TOP CATEGORIES
------------------------------------------------------------
Series([], Name: Amount, dtype: object)

TOP VENDORS
------------------------------------------------------------
Series([], Name: Amount, dtype: object)

SPENDING ARCHETYPES
------------------------------------------------------------

============================================================

In [ ]:
print(df["Date"].head(20))

0    2024-01-01
1           NaT
2           NaT
3    2024-01-01
4           NaT
5    2024-01-01
6    2024-01-01
7           NaT
8    2024-01-02
9           NaT
10          NaT
11          NaT
12          NaT
13          NaT
14          NaT
15          NaT
16   2024-01-02
17          NaT
18          NaT
19          NaT
Name: Date, dtype: datetime64[ns]

In [ ]:
print(df["Date"].unique()[:20])

<DatetimeArray>
['2024-01-01 00:00:00',                 'NaT', '2024-01-02 00:00:00',
 '2024-01-03 00:00:00', '2024-01-04 00:00:00', '2024-01-05 00:00:00',
 '2024-01-07 00:00:00', '2024-01-08 00:00:00', '2024-01-09 00:00:00',
 '2024-01-10 00:00:00', '2024-01-12 00:00:00', '2024-01-14 00:00:00',
 '2024-01-15 00:00:00', '2024-01-18 00:00:00', '2024-01-20 00:00:00',
 '2024-01-21 00:00:00', '2024-01-24 00:00:00', '2024-01-25 00:00:00',
 '2024-01-26 00:00:00', '2024-01-28 00:00:00']
Length: 20, dtype: datetime64[ns]

In [ ]:
print(df.columns.tolist())

['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode', 'Ref', 'Year', 'Month', 'Month_Name', 'Day', 'Day_Name', 'Hour', 'Vendor', 'Category']

In [ ]:
print("=" * 60)
print("                 SPENDDNA REPORT")
print("=" * 60)

print("\nTRANSACTION SUMMARY")
print("-" * 60)

print(f"Total Credits : ₹{total_credits:,.2f}")
print(f"Total Debits  : ₹{total_debits:,.2f}")
print(f"Net Change    : ₹{net_change:,.2f}")
print(f"Savings Rate  : {savings_rate:.2f}%")
print(f"Transactions  : {len(df)}")

print("\nTOP CATEGORIES")
print("-" * 60)

print(top_categories.head(5))

print("\nTOP VENDORS")
print("-" * 60)

print(top_vendors.head(5))

print("\nSPENDING ARCHETYPES")
print("-" * 60)

for archetype in archetypes:
    print("→", archetype)

print("\n" + "=" * 60)

============================================================
                 SPENDDNA REPORT
============================================================

TRANSACTION SUMMARY
------------------------------------------------------------
Total Credits : ₹0.00
Total Debits  : ₹0.00
Net Change    : ₹0.00
Savings Rate  : nan%
Transactions  : 1328

TOP CATEGORIES
------------------------------------------------------------
Series([], Name: Amount, dtype: object)

TOP VENDORS
------------------------------------------------------------
Series([], Name: Amount, dtype: object)

SPENDING ARCHETYPES
------------------------------------------------------------

============================================================